import { NextResponse } from 'next/server'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

export async function POST(req: Request) {

  try {

    const data = await req.json()

    const pdfDoc = await PDFDocument.create()
    const page = pdfDoc.addPage([600, 750])

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica)

    let y = 700

    function draw(text: string, size = 12) {
      page.drawText(text, {
        x: 50,
        y,
        size,
        font,
        color: rgb(0, 0, 0)
      })
      y -= 22
    }

    draw('Beveez Tech Website Performance Audit', 18)

    y -= 10

    draw(`Website: ${data.url}`)
    draw(`Performance Score: ${data.performance}`)
    draw(`SEO Score: ${data.seo}`)
    draw(`Accessibility Score: ${data.accessibility}`)
    draw(`Best Practices Score: ${data.bestPractices}`)

    y -= 20
    draw('Issues Detected:', 14)

    data.issues?.forEach((issue: string) => {
      draw(`• ${issue}`)
    })

    y -= 20
    draw('Recommended Optimizations:', 14)

    data.recommendations?.forEach((rec: string) => {
      draw(`• ${rec}`)
    })

    y -= 30
    draw('Generated by Beveez Tech', 10)

    const pdfBytes = await pdfDoc.save()

    // Convert Uint8Array → ArrayBuffer
    const buffer = new Uint8Array(pdfBytes).buffer

    const blob = new Blob([buffer], { type: 'application/pdf' })

    return new NextResponse(blob, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename=website-audit-report.pdf'
      }
    })

  } catch (error) {

    console.error('PDF GENERATION ERROR:', error)

    return NextResponse.json(
      { error: 'Unable to generate PDF report' },
      { status: 500 }
    )

  }

}